# 
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
#
# kustomize build deployments/services/training-pipeline | kubectl apply -f -
#
---
# yaml-language-server: $schema=https://kubernetes.io/schema/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rwml
resources:
  - ./training-pipeline-cm.yaml
  - ./training-pipeline-j.yaml

