apiVersion: batch/v1
kind: Job
metadata:
  name: training-pipeline-job
spec:
  template:
    spec:
      containers:
      - name: training-pipeline
        image: training-pipeline-image
        env:
        - name: RISINGWAVE_HOST
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: RISINGWAVE_HOST
        - name: RISINGWAVE_PORT
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: RISINGWAVE_PORT
        - name: RISINGWAVE_USER
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: RISINGWAVE_USER
        - name: RISINGWAVE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: RISINGWAVE_DATABASE
        - name: SYMBOL
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: SYMBOL
        - name: DAYS_IN_PAST
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: DAYS_IN_PAST
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map 
              key: CANDLE_SECONDS
        - name: PREDICTION_HORIZON_SECONDS
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: PREDICTION_HORIZON_SECONDS 
        - name: N_ROWS_FOR_DATA_PROFILING
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: N_ROWS_FOR_DATA_PROFILING
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: training-pipeline-config-map
              key: MLFLOW_TRACKING_URI
        - name: TRAIN_TEST_SPLIT_RATIO
          valueFrom:    
            configMapKeyRef:
              name: training-pipeline-config-map
              key: TRAIN_TEST_SPLIT_RATIO
        - name: HYPERPARAM_SEARCH_TRIALS
          valueFrom:
            configMapKeyRef:  
              name: training-pipeline-config-map
              key: HYPERPARAM_SEARCH_TRIALS
        - name: HYPERPARAM_SPLITS
          valueFrom:
            configMapKeyRef:  
              name: training-pipeline-config-map
              key: HYPERPARAM_SPLITS
        - name: TOP_N_MODELS
          valueFrom:
            configMapKeyRef:  
              name: training-pipeline-config-map
              key: TOP_N_MODELS 
        - name: TRESHOLD_NULL_VALUES
          valueFrom:
            configMapKeyRef:  
              name: training-pipeline-config-map
              key: TRESHOLD_NULL_VALUES
        - name: TRESHOLD_SELECT_MODEL
          valueFrom:
            configMapKeyRef:  
              name: training-pipeline-config-map 
              key: TRESHOLD_SELECT_MODEL
      restartPolicy: OnFailure
          