apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  labels:
    app: candles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        image: candles-image
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: candles-config-map
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_INPUT
          valueFrom:
            configMapKeyRef:
              name: candles-config-map
              key: KAFKA_TOPIC_INPUT
        - name: KAFKA_TOPIC_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: candles-config-map
              key: KAFKA_TOPIC_OUTPUT
        - name: TIMEFRAME_CANDLE
          valueFrom:
            configMapKeyRef:
              name: candles-config-map
              key: TIMEFRAME_CANDLE