apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: bitcoin-predictor
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: trades-image
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: KAFKA_TOPIC_NAME
        - name: LIVE_OR_HISTORICAL
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: LIVE_OR_HISTORICAL
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: KAFKA_HOST
        - name: CRYPTOS_ID
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: CRYPTOS_ID
        - name: LAST_N_DAYS_REST_API
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: LAST_N_DAYS_REST_API
        - name: KAFKA_TOPIC_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: trades-config-map
              key: KAFKA_TOPIC_OUTPUT
              
