apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AccessKeyID: 6Wl2QFJZGrAB8LSMcGB0
  SecretKey: jzZpBLUK6WXBXj919NkIYGtEEBudNUkIIzpGaxUY