apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AccessKeyID: 9RGghmolxa9wvF2l5ZIZ
  SecretKey: et3GNSGXnqCflQyXn9croiHsHV5BMDimGG67c5MG