artifact_location: /Users/josemiguelvilchesfierro/Documents/study/my_bitcoin_predictor/services/predictor/src/None/0
creation_time: 1747404309089
experiment_id: '0'
last_update_time: 1747404309089
lifecycle_stage: active
name: Default
