apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: get-trades-image
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_HOST
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"