apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  KAFKA_HOST: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
  CRYPTOS_ID: '["BTC/USD","ETH/USD"]'
  LIVE_OR_HISTORICAL: historical
  LAST_N_DAYS_REST_API: '30'
  TIMEFRAME_CANDLE: '60'
  MAX_CANDLE_STATE: '70'
  LIST_SMA_PERIODS: '[7, 14, 21, 60]'
  KAFKA_TOPIC_INPUT: trades_historical
  KAFKA_TOPIC_OUTPUT: candles_historical
  KAFKA_TOPIC_TECHNICAL_INDICATORS: technical_indicators
  RISINGWAVE_TABLE_NAME: technical-indicators


---

apiVersion: batch/v1
kind: Job
metadata:
  name: trades-historical
  labels:
    app: trades-historical
spec:
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      restartPolicy: Never
      containers:
      - name: trades-historical
        image: get-trades-image
        imagePullPolicy: Never
        env:
        - name: LIVE_OR_HISTORICAL
          value: "historical"
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_TOPIC_OUTPUT
        - name: CRYPTOS_ID
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CRYPTOS_ID
        - name: LAST_N_DAYS_REST_API
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: LAST_N_DAYS_REST_API

---

apiVersion: batch/v1
kind: Job
metadata:
  name: candles-historical
  labels:
    app: candles-historical
spec:
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      restartPolicy: Never
      containers:
      - name: candles-historical
        image: candles-image
        imagePullPolicy: Never
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_INPUT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_TOPIC_INPUT
        - name: KAFKA_TOPIC_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_TOPIC_OUTPUT
        - name: TIMEFRAME_CANDLE
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: TIMEFRAME_CANDLE
        - name: MAX_CANDLE_STATE
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: MAX_CANDLE_STATE
        - name: LIST_SMA_PERIODS
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: LIST_SMA_PERIODS
        - name: CRYPTOS_ID
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CRYPTOS_ID

---

apiVersion: batch/v1
kind: Job
metadata:
  name: technical-indicators
  labels:
    app: technical-indicators
spec:
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      containers:
      - name: technical-indicators
        image: technical-indicators-image
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_INPUT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_TOPIC_INPUT
        - name: KAFKA_TOPIC_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: KAFKA_TOPIC_OUTPUT
        - name: TIMEFRAME_CANDLE
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: TIMEFRAME_CANDLE
        - name: MAX_CANDLE_STATE
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: MAX_CANDLE_STATE
        - name: LIST_SMA_PERIODS
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: LIST_SMA_PERIODS
        - name: RISINGWAVE_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: RISINGWAVE_TABLE_NAME
          
